version: '3'

services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - /morenote/nginx/data/front:/usr/share/nginx/html
      - /morenote/nginx/www:/var/www
    environment:
       NGINX_PORT: 80
    privileged: true

  postgres:
    restart: always
    container_name: postgres
    image: postgres:14-alpine3.15
    ports:
      - 55433:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: mypassword
       ALLOW_IP_RANGE: 0.0.0.0/0
       TZ: Asia/Shanghai
    volumes:
      - /morenote/postgres-data:/var/lib/postgresql
    privileged: true

  minio:
    restart: always
    container_name: minio
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
     - 9000:9000
     - 9001:9001
    volumes:
      - /morenote/minio/data:/data
      - /morenote/minio/config:/root/.minio
    environment:
      MINIO_ACCESS_KEY: username
      MINIO_SECRET_KEY: password
    privileged: true
  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    privileged: true
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5671:5671
      - 5672:5672
      - 4369:4369
      - 25672:25672
      - 15671:15671
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
  elasticsearch:
    restart: always
    container_name:  elasticsearch
    image: elasticsearch:8.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms128m -Xmx1g
    




    