# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - 'master'
    tags:
      - 'v0.0.*'
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: env info
      run: ls & pwd
    - name: cd project
      run:  cd Src/MoreNote 
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Restore dependencies
      working-directory: Src/MoreNote
      run: pwd && ls && dotnet restore
    - name: Publish
      working-directory: Src/MoreNote
      run:  dotnet publish -f net8.0 -c Release --self-contained false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context:  ./Src/MoreNote
        file: ./Dockerfile
        platforms: |
            linux/amd64
            linux/arm64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/morenote:${{ github.sha }}