name: MoreNote.NET Core

on:
  push:
    branches: [ master ]
    tags:        
      - v1             # Push events to v1 tag
      - v2.* 
  pull_request:
    branches: [ master ]
    tags:        
      - v1.*            # Push events to v1 tag
      - v2.* 
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #安装C#的linux环境
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    #还原依赖
    - name: Install dependencies
      run: dotnet restore
    #编译
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #运行测试
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    #发布代码版本
    - name: Publish
      run: dotnet publish -c Release  -o bin/publish/morenote --no-self-contained  --no-restore --no-build
    #安装ssh
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    #部署到远程服务器
    - name: deploy to server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "./bin/publish/morenote"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
    #停止服务&&移除旧的程序文件&&拷贝新的程序文件&&启动服务
    - name: server restart
      uses: garygrossgarten/github-action-ssh@release
      with:
       command: supervisord ctl stop  MoreNote &&  rm -rf /www/morenote.top/app && mkdir /www/morenote.top/app && \cp -rf  /github/actions/morenote/*  /www/morenote.top/app && supervisord ctl start MoreNote
       host: ${{ secrets.SERVER_IP }}
       port : ${{ secrets.SERVER_PORT }}
       username: ${{ secrets.USERNAME }}
       privateKey: ${{ secrets.DEPLOY_KEY}}