name: MoreNote.NET Core

on:
  push:
    branches: 
       - master
  pull_request:
    branches:
       - master
   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    #安装C#的linux环境
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    #还原依赖
    - name: Install dependencies
      run: dotnet restore
    #编译
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #运行测试
    - name: Test
      run: dotnet test --no-restore --verbosity normal
