name: .NET Core

on:
  push:
    branches: [ hyfree-patch-1 ]
  pull_request:
    branches: [ hyfree-patch-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
       #安装ssh
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    #部署到远程服务器
    - name: deploy to server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY}}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "./"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
    #SSH命令
      
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
       command: ls -a
       host: ${{ secrets.SERVER_IP }}
       port : ${{ secrets.SERVER_PORT }}
       username: ${{ secrets.USERNAME }}
       privateKey: ${{ secrets.DEPLOY_KEY}}
 
